version: "3.7"

services: 
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app
    # volumes: 
    #   - ./:/home/projects/flask-azure-playground
    ports: 
      - "8081:5000"
  # server:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - 8080:80