version: "3.7"

services: 
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app
    # volumes: 
    #   - flask-app-volume:/home/projects/flask-azure-playground
    # ports: 
    #   - "8081:5000"
    networks:
      my-network:
        aliases:
          - flask-app
  server:
    image: nginx:latest
    container_name: nginx_server
    depends_on:
      - web
    volumes:
      # - flask-app-volume:/home/projects/flask-azure-playground
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - my-network

networks:
  my-network:
# volumes: 
#   flask-app-volume: